@host = localhost:5000

// Reordering them so it kind follows a natural flow

// Create User
POST http://{{host}}/api/users HTTP/1.1
content-type: application/json
    
{
    "username": "Bob",
    "password": "dangWaffles",
    "name": "BOBBY"
}

###

// Login to profile
POST http://{{host}}/api/signin HTTP/1.1
content-type: application/json
    
{
    "username": "John3",
    "password": "waffles"
}

###

// Welcome logged in user
POST http://{{host}}/api/welcome HTTP/1.1
content-type: application/json

{
    "username": "John3",
    "password": "waffles"
}

###

// Send Friend Request
POST http://{{host}}/api/sendFriendRequest HTTP/1.1
content-type: application/json

{
    "sender": "G",
    "reciever": "YEEE"
}

###

// Accept Friend Request
POST http://{{host}}/api/acceptFriendRequest HTTP/1.1
content-type: application/json

{
    "sender": "GOD",
    "reciever": "MALE"
}

###

// Remove Friend 
POST http://{{host}}/api/removeFriend HTTP/1.1
content-type: application/json

{
    "sender": "ALPHA",
    "reciever": "MALE"
}

###
// Refresh the page for logged in user
http://{{host}}/api/refresh HTTP/1.1
content-type: application/json

{
    "username": "John3",
    "password": "waffles"
}

###

// Logout user
POST http://{{host}}/api/logout HTTP/1.1
content-type: application/json

###

// Add a reservation
POST http://localhost:5000/api/reservations HTTP/1.1
content-type: application/json

{
    "start_date": "2006-11-15",
    "end_date": "2006-11-25",
    "guest_name": "Adam Wujtulewski",
    "guest_username": "Adam Wujtulewski",
    "guest_email": "adamwuj@gmail.com",
    "host_name": "John Doe",
    "host_username": "JohnDoe",
    "host_email": "johndoe@gmail.com",
    "host_address": "London, UK",
    "host_country": "United Kingdom",
    "status": "pending"
}

###
// Add a listing
POST http://localhost:5000/api/listings HTTP/1.1
content-type: application/json
{
    "start_date": "2006-01-01",
    "end_date": "2006-01-03",
    "host_name": "Jake Doe",
    "host_username": "JakeDoe",
    "host_email": "jakedoe@gmail.com",
    "host_address": "London, UK",
    "host_country": "United Kingdom",
    "capacity": 4,
    "status": "pending"
}

###

// Get User By ID
GET http://{{host}}/api/users/5 HTTP/1.1
content-type: application/json

###

// Get All User OR search for a user (?username= exampleName)
GET http://{{host}}/api/users/ HTTP/1.1
content-type: application/json

###
// Get users living close to a desired location
GET http://{{host}}/api/search?location=Oxford%2C%20England&maxDistance=1000&unit=mi HTTP/1.1
content-type: application/json

###

// Update User Basic Info
PUT http://{{host}}/api/users/6 HTTP/1.1
content-type: application/json

{
    "username": "MATT",
    "password": "acktumally",
    "biography": "YEEA!"
}

###

// Update User Detailed Info
PUT http://{{host}}/api/users/6 HTTP/1.1
content-type: application/json

{
    "birthday": "updated!",
    "email": "updated",
    "phone": "updated!",
    "gender": "updated!",
    "address_1": "updated!",
    "address_2": "updated!",
    "address_3": "updated!",
    "biography": "updated!",
    "country": "updated!",
    "emergency_contact_name": "updated!",
    "emergency_contact_phone_number": "updated!",
    "emergency_contact_address": "updated!"
}

###

// Delete User
DELETE http://{{host}}/api/users/57 HTTP/1.1
content-type: application/json